### ISSUE TITLE
Add a better way of determining if a rule input is "Any'

### ISSUE THREAD

**Issue by kislayverma** [kislayverma/Rulette#31]
The only way to do this right now is to check for NULL or "". This leaks out implementation detail of what constitutes 'Any', in addition to making the calling code ugly and fragile.

We should build a better interface to this info (maybe via a 'isAny()' method on rule input class)

**Comment by kapilratnani** [comment]
We can go the cron way. Any = '*'

**Comment by kislayverma** [comment]
We already have null == Any. Im thinking to just expose this via a method called isAny() on RuleInput

**Comment by kislayverma** [comment]
Check https://github.com/kislayverma/Rulette/pull/32
